version: '3.8'

services:
  app:
    build: .
    container_name: hotel_app_test
    environment:
      - RAILWAY_ENVIRONMENT=testing
      - DATABASE_URL=postgresql://postgres:password123@db_test:5432/hotel_db_test
      - FLASK_APP=src/api/app.py
      - FLASK_ENV=testing
      - PYTHONPATH=/app
    depends_on:
      - db_test
    volumes:
      - .:/app
    command: pytest tests/ -v --disable-warnings

  db_test:
    image: postgres:15
    container_name: hotel_db_test
    environment:
      POSTGRES_DB: hotel_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5434:5432"
    volumes:
      - hotel_db_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hotel_db_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  hotel_db_test_data: